baseURL = 'https://Oolongk.github.io/aws-project/'
defaultContentLanguage = 'vi'
theme = 'learn'

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = 'workshop'
  showVisitedLinks = true
  disableSearch = false
  disableLanguageSwitching = false
  disableLanguageSwitchingButton = false
  custom_css = ["css/custom.css"]

[languages]
  [languages.vi]
    contentDir = 'content/vi'
    title = 'AWS FCAJ Capstone Report - Nguyễn Ngọc Tuấn Khanh'
    weight = 1
    languageName = 'Tiếng Việt'
    label = 'Tiếng Việt'

  [languages.en]
    contentDir = 'content/en'
    title = 'AWS FCAJ Capstone Report - Nguyen Ngoc Tuan Khanh'
    weight = 2
    languageName = 'English'
    label = 'English'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true