baseURL = 'https://Oolongk.github.io/aws-project/'
locale = 'vi'
defaultContentLanguage = 'vi'
title = 'AWS FCJ Capstone Report - Nguyễn Ngọc Tuấn Khanh'
theme = 'learn'

[params]
  themeVariant = 'blue'
  showVisitedLinks = true
  disableSearch = false
  disableLanguageSwitching = true